leftnav:
- identifier: 5e35bcb9-9645-e7a4-ccab-bbd04fe593bc
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 29c7b5c0-685d-ffa8-c893-a29f192ddbff
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 03e6d0d6-2c86-9a09-2190-2b1a3feadd90
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: ddacaa52-4df3-e1da-80fc-9cc44f0ae876
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 83f5929e-c09c-2e1e-ddf4-a03218c92c6f
  name: Projects
  pageRef: /pages/projects
  weight: 50
